package models.enums;

public enum ArmorCategory {
    HEAVY_BREASTPLATE,
    HEAVY_LEGGNGS,
    HEAVY_BOOTS,
    HEAVY_HELMENT,
    LIGHTBREAST_PLATE,
    LIGHT_LEGGNGS,
    LIGHT_BOOTS,
    LIGHT_HELMENT,
    BREASTPLATE,
    LEGGINGS,
    BOOTS,
    HELMET
}
