package models.enums;

public enum ArmorCategory {
    HEAVYBREASTPLATE,
    HEAVYLEGGNGS,
    HEAVYBOOTS,
    HEAVYHELMENT,
    LIGHTBREASTPLATE,
    LIGHTLEGGNGS,
    LIGHTBOOTS,
    LIGHTHELMENT,
    BREASTPLATE,
    LEGGINGS,
    BOOTS,
    HELMET
}
