package models.enums;

public enum CoolConsumabelName {
    HEARTROOTTONIC,
    CRIMSONREMEDY,
    LIFEBLOOMBREW,
    VITALITYINFUSION,
    ELIXIROFRENEWAL,
    SUNLEAFEXTRACT,
    HEARTFIREDRAUGHT,
    POTIONOFREBIRTH,
    LIFEESSENCEFLASK,
    BLOODPETALMIXTURE,
    EMBERBURSTFLASK,
    VENOMSTRIKEVIAL,
    SHADOWROTPOISON,
    ACIDBITEBOTTLE,
    INFERNOBOMB,
    CORROSIONCAPSULE,
    TEMPESTCHARGE,
    FROSTBITEGRENADE,
    THUNDERCLAPVIAL,
    ASHENFURYMIX,

}
