package models.enums;

public enum CoolConsumabelName {
    HEARTROOT_TONIC,
    CRIMSON_REMEDY,
    LIFEBLOOM_BREW,
    VITALITY_INFUSION,
    ELIXIR_OF_RENEWAL,
    SUNLEAFEX_TRACT,
    HEARTFIRE_DRAUGHT,
    POTIONOFREBIRTH,
    LIFEESSENCE_FLASK,
    BLOODPETAL_MIXTURE,
    EMBERBURST_FLASK,
    VENOMSTRIKE_VIAL,
    SHADOWROT_POISON,
    ACIDBITE_BOTTLE,
    INFERNO_BOMB,
    CORROSION_CAPSULE,
    TEMPEST_CHARGE,
    FROSTBITE_GRENADE,
    THUNDERCLAP_VIAL,
    ASHENFURY_MIX
}
